# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "*"
permissions:
  contents: write
  discussions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install -y libxcursor-dev libxxf86vm-dev libxrandr-dev libxinerama-dev libxi-dev libglx-dev libgl1-mesa-dev
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Build-Linux
        run: CGO_ENABLED=1 go build -v ./...

      - name: Build-Windows
        run: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC="x86_64-w64-mingw32-gcc" go build

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "curver,curver.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
